/**
 * @packageDocumentation
 *
 * This module provides functionality to build and bundle an Obsidian plugin using esbuild.
 * It includes functions to handle the build process based on different build modes (development or production),
 * and it sets up various esbuild plugins to preprocess, lint, fix source maps, and copy files to the Obsidian plugins folder.
 */

/* v8 ignore start -- esbuild-based build pipeline with sass/svelte plugins and file watchers; requires a live esbuild context. */

import type {
  BuildContext,
  BuildOptions,
  Plugin
} from 'esbuild';

import { context } from 'esbuild';
// eslint-disable-next-line import-x/no-rename-default -- We need a temp variable to apply `extractDefaultExportInterop()` fix below.
import sassPlugin_ from 'esbuild-sass-plugin';

import { extractDefaultExportInterop } from '../../../ObjectUtils.ts';
import { ObsidianPluginRepoPaths } from '../../../obsidian/Plugin/ObsidianPluginRepoPaths.ts';
import { join } from '../../../Path.ts';
import { ensureNonNullable } from '../../../TypeGuards.ts';
import { buildCompile } from '../../build.ts';
import { CliTaskResult } from '../../CliUtils.ts';
import {
  builtinModules,
  cp,
  existsSync,
  loadEnvFile,
  mkdir,
  process,
  rm,
  writeFile
} from '../../NodeModules.ts';
import { readPackageJson } from '../../Npm.ts';
import { resolvePathFromRoot } from '../../Root.ts';
import { copyToObsidianPluginsFolderPlugin } from './copyToObsidianPluginsFolderPlugin.ts';
import { customEsbuildOptionsPlugin } from './customEsbuildOptionsPlugin.ts';
import { fixEsmPlugin } from './fixEsmPlugin.ts';
import { fixSourceMapsPlugin } from './fixSourceMapsPlugin.ts';
import { preprocessPlugin } from './preprocessPlugin.ts';
import { renameCssPlugin } from './renameCssPlugin.ts';
import { svelteWrapperPlugin } from './svelteWrapperPlugin.ts';

const sassPlugin = extractDefaultExportInterop(sassPlugin_);

/**
 * Enumeration representing the build modes.
 */
export enum BuildMode {
  /** Development mode for building the plugin */
  Development,
  /** Production mode for building the plugin */
  Production
}

/**
 * Banner text to be included at the top of the generated files.
 */
export const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

/**
 * Options for {@link buildObsidianPlugin}.
 */
export interface BuildObsidianPluginParams {
  /**
   * Custom esbuild plugins to be used during the build process.
   */
  readonly customEsbuildPlugins?: Plugin[];

  /**
   * Customizes the `esbuild` options.
   */
  readonly customizeEsbuildOptions?: (options: BuildOptions) => void;

  /**
   * A build mode, either `Development` or `Production`
   */
  readonly mode: BuildMode;

  /**
   * A folder for Obsidian configuration. Defaults to the `OBSIDIAN_CONFIG_FOLDER` environment variable.
   */
  readonly obsidianConfigFolder?: string;
}

interface ObsidianPluginBuilderEnv {
  OBSIDIAN_CONFIG_FOLDER: string;
}

/**
 * Builds the Obsidian plugin based on the specified mode and configuration folder.
 *
 * @param params - The parameters for building the plugin.
 * @returns A {@link Promise} that resolves to a {@link CliTaskResult} indicating the success or failure of the build.
 */
export async function buildObsidianPlugin(params: BuildObsidianPluginParams): Promise<CliTaskResult> {
  await buildCompile();
  const envPath = resolvePathFromRoot('.env');
  if (envPath && existsSync(envPath)) {
    loadEnvFile(envPath);
  }
  const obsidianPluginBuilderEnv = process.env as Partial<ObsidianPluginBuilderEnv>;

  const obsidianConfigFolder = params.obsidianConfigFolder ?? obsidianPluginBuilderEnv.OBSIDIAN_CONFIG_FOLDER ?? '';
  const isProductionBuild = params.mode === BuildMode.Production;

  const distFolder = ensureNonNullable(
    resolvePathFromRoot(isProductionBuild ? ObsidianPluginRepoPaths.DistBuild : ObsidianPluginRepoPaths.DistDev),
    'Could not determine the dist folder'
  );

  if (existsSync(distFolder)) {
    await rm(distFolder, { recursive: true });
  }
  await mkdir(distFolder, { recursive: true });

  const distFileNames = [
    ObsidianPluginRepoPaths.ManifestJson
  ];
  if (!isProductionBuild) {
    await writeFile(join(distFolder, ObsidianPluginRepoPaths.HotReload), '', 'utf-8');
  }

  for (const fileName of distFileNames) {
    const localFile = ensureNonNullable(resolvePathFromRoot(fileName), `Could not determine the local file for ${fileName}`);
    const distFile = join(distFolder, fileName);

    if (existsSync(localFile)) {
      await cp(localFile, distFile);
    }
  }

  const distPath = join(distFolder, ObsidianPluginRepoPaths.MainJs);
  const cssPath = join(distFolder, ObsidianPluginRepoPaths.StylesCss);

  const packageJson = await readPackageJson();
  const pluginName = packageJson.name ?? '(unknown)';

  const buildOptions: BuildOptions = {
    banner: {
      js: banner
    },
    bundle: true,
    conditions: ['browser'],
    entryPoints: [
      ensureNonNullable(
        resolvePathFromRoot(join(ObsidianPluginRepoPaths.Src, ObsidianPluginRepoPaths.MainTs)),
        'Could not determine the entry point for the plugin'
      )
    ],
    external: [
      'obsidian',
      'electron',
      '@codemirror/autocomplete',
      '@codemirror/collab',
      '@codemirror/commands',
      '@codemirror/language',
      '@codemirror/lint',
      '@codemirror/search',
      '@codemirror/state',
      '@codemirror/view',
      '@lezer/common',
      '@lezer/highlight',
      '@lezer/lr',
      'esbuild',
      'eslint',
      ...builtinModules
    ],
    format: 'cjs',
    keepNames: true,
    logLevel: 'info',
    minify: isProductionBuild,
    outfile: distPath,
    platform: 'node',
    plugins: [
      customEsbuildOptionsPlugin(params.customizeEsbuildOptions?.bind(params)),
      svelteWrapperPlugin(isProductionBuild),
      sassPlugin({
        sourceMap: !isProductionBuild
      }),
      renameCssPlugin(distFolder),
      preprocessPlugin(),
      fixEsmPlugin(),
      fixSourceMapsPlugin(isProductionBuild, [distPath, cssPath], pluginName),
      ...params.customEsbuildPlugins ?? [],
      copyToObsidianPluginsFolderPlugin(isProductionBuild, distFolder, obsidianConfigFolder, pluginName)
    ],
    sourcemap: isProductionBuild ? false : 'inline',
    target: 'esnext',
    treeShaking: true
  };

  const buildContext = await context(buildOptions);
  return await invokeEsbuild(buildContext, isProductionBuild);
}

/**
 * Invokes the build process with the provided build context.
 *
 * @param buildContext - The build context generated by esbuild.
 * @param isProductionBuild - A boolean indicating whether the build is a production build.
 * @returns A {@link Promise} that resolves to a {@link CliTaskResult} indicating the success or failure of the build.
 */
export async function invokeEsbuild(buildContext: BuildContext, isProductionBuild: boolean): Promise<CliTaskResult> {
  if (isProductionBuild) {
    const result = await buildContext.rebuild();
    const isSuccess = result.errors.length === 0 && result.warnings.length === 0;
    return CliTaskResult.Success(isSuccess);
  }
  await buildContext.watch();
  return CliTaskResult.DoNotExit();
}

/**
 * Builds the Obsidian plugin in production mode using esbuild.
 *
 * @param params - Optional build parameters (mode is set to Production automatically).
 * @returns A {@link Promise} that resolves when the build is complete.
 */
export async function build(params?: Omit<BuildObsidianPluginParams, 'mode'>): Promise<void> {
  const result = await buildObsidianPlugin({ ...params, mode: BuildMode.Production });
  result.throwOnFailure();
}

/**
 * Builds the Obsidian plugin in development mode using esbuild with watch.
 *
 * @param params - Optional build parameters (mode is set to Development automatically).
 * @returns A {@link Promise} that resolves when the dev build starts (keeps process alive for watch mode).
 */
export async function dev(params?: Omit<BuildObsidianPluginParams, 'mode'>): Promise<void> {
  await buildObsidianPlugin({ ...params, mode: BuildMode.Development });
}

/* v8 ignore stop */
