/**
 * @file
 *
 * This module provides functionality to build and bundle an Obsidian plugin using esbuild.
 * It includes functions to handle the build process based on different build modes (development or production),
 * and it sets up various esbuild plugins to preprocess, lint, fix source maps, and copy files to the Obsidian plugins folder.
 */

/* v8 ignore start -- esbuild-based build pipeline with sass/svelte plugins and file watchers; requires a live esbuild context. */

import type {
  BuildContext,
  BuildOptions as EsbuildOptions,
  Plugin
} from 'esbuild';

import { context } from 'esbuild';
// eslint-disable-next-line import-x/no-rename-default -- We need a temp variable to apply `extractDefaultExportInterop()` fix below.
import sassPlugin_ from 'esbuild-sass-plugin';
import {
  existsSync,
  watch
} from 'node:fs';
import {
  cp,
  mkdir,
  rm,
  writeFile
} from 'node:fs/promises';
import { builtinModules } from 'node:module';
import process, { loadEnvFile } from 'node:process';

import { invokeAsyncSafely } from '../../../async.ts';
import { extractDefaultExportInterop } from '../../../object-utils.ts';
import { ObsidianPluginRepoPaths } from '../../../obsidian/plugin/obsidian-plugin-repo-paths.ts';
import { join } from '../../../path.ts';
import { ensureNonNullable } from '../../../type-guards.ts';
import { CliTaskResult } from '../../cli-utils.ts';
import { npmRun } from '../../npm-run.ts';
import { readPackageJson } from '../../npm.ts';
import { resolvePathFromRoot } from '../../root.ts';
import { copyToObsidianPluginsFolderPlugin } from './copy-to-obsidian-plugins-folder-plugin.ts';
import { customEsbuildOptionsPlugin } from './custom-esbuild-options-plugin.ts';
import { fixEsmPlugin } from './fix-esm-plugin.ts';
import { fixSourceMapsPlugin } from './fix-source-maps-plugin.ts';
import { preprocessPlugin } from './preprocess-plugin.ts';
import { renameCssPlugin } from './rename-css-plugin.ts';
import { svelteWrapperPlugin } from './svelte-wrapper-plugin.ts';

const sassPlugin = extractDefaultExportInterop(sassPlugin_);

/**
 * Debounce window for restarting a development build after `node_modules` changes. A reinstall or a
 * dependency rebuild touches many files in quick succession, so we wait for the churn to settle
 * before restarting once.
 */
const NODE_MODULES_RESTART_DEBOUNCE_IN_MILLISECONDS = 1000;

/**
 * Enumeration representing the build modes.
 */
export enum BuildMode {
  /** Development mode for building the plugin */
  Development,
  /** Production mode for building the plugin */
  Production
}

/**
 * Banner text to be included at the top of the generated files.
 */
export const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

/**
 * Options for {@link buildObsidianPlugin}.
 */
export interface BuildObsidianPluginParams {
  /**
   * Custom esbuild plugins to be used during the build process.
   */
  readonly customEsbuildPlugins?: Plugin[];

  /**
   * Customizes the `esbuild` options.
   */
  customizeEsbuildOptions?(options: EsbuildOptions): void;

  /**
   * A build mode, either `Development` or `Production`
   */
  readonly mode: BuildMode;

  /**
   * A folder for Obsidian configuration. Defaults to the `OBSIDIAN_CONFIG_FOLDER` environment variable.
   */
  readonly obsidianConfigFolder?: string;
}

/**
 * Build parameters without the mode field, for use with {@link build} and {@link dev}.
 */
export interface BuildOptions {
  /**
   * Custom esbuild plugins to be used during the build process.
   */
  readonly customEsbuildPlugins?: Plugin[];

  /**
   * Customizes the `esbuild` options.
   */
  customizeEsbuildOptions?(options: EsbuildOptions): void;

  /**
   * A folder for Obsidian configuration. Defaults to the `OBSIDIAN_CONFIG_FOLDER` environment variable.
   */
  readonly obsidianConfigFolder?: string;
}

interface ObsidianPluginBuilderEnv {
  OBSIDIAN_CONFIG_FOLDER: string;
}

/**
 * Builds the Obsidian plugin in production mode using esbuild.
 *
 * @param options - Optional build parameters (mode is set to Production automatically).
 * @returns A {@link Promise} that resolves when the build is complete.
 */
export async function build(options?: BuildOptions): Promise<void> {
  const result = await buildObsidianPlugin({ ...options, mode: BuildMode.Production });
  result.throwOnFailure();
}

/**
 * Builds the Obsidian plugin based on the specified mode and configuration folder.
 *
 * @param params - The parameters for building the plugin.
 * @returns A {@link Promise} that resolves to a {@link CliTaskResult} indicating the success or failure of the build.
 */
export async function buildObsidianPlugin(params: BuildObsidianPluginParams): Promise<CliTaskResult> {
  await npmRun('build:compile');
  const envPath = resolvePathFromRoot({ path: '.env' });
  if (envPath && existsSync(envPath)) {
    loadEnvFile(envPath);
  }
  const obsidianPluginBuilderEnv = process.env as Partial<ObsidianPluginBuilderEnv>;

  const obsidianConfigFolder = params.obsidianConfigFolder ?? obsidianPluginBuilderEnv.OBSIDIAN_CONFIG_FOLDER ?? '';
  const isProductionBuild = params.mode === BuildMode.Production;

  const distFolder = ensureNonNullable(
    resolvePathFromRoot({ path: isProductionBuild ? ObsidianPluginRepoPaths.DistBuild : ObsidianPluginRepoPaths.DistDev }),
    'Could not determine the dist folder'
  );

  if (existsSync(distFolder)) {
    await rm(distFolder, { recursive: true });
  }
  await mkdir(distFolder, { recursive: true });

  const distFileNames = [
    ObsidianPluginRepoPaths.ManifestJson
  ];
  if (!isProductionBuild) {
    await writeFile(join(distFolder, ObsidianPluginRepoPaths.HotReload), '', 'utf-8');
  }

  for (const fileName of distFileNames) {
    const localFile = ensureNonNullable(resolvePathFromRoot({ path: fileName }), `Could not determine the local file for ${fileName}`);
    const distFile = join(distFolder, fileName);

    if (existsSync(localFile)) {
      await cp(localFile, distFile);
    }
  }

  const distPath = join(distFolder, ObsidianPluginRepoPaths.MainJs);
  const cssPath = join(distFolder, ObsidianPluginRepoPaths.StylesCss);

  const packageJson = await readPackageJson();
  const pluginName = packageJson.name ?? '(unknown)';

  const buildOptions: EsbuildOptions = {
    banner: {
      js: banner
    },
    bundle: true,
    conditions: ['browser'],
    entryPoints: [
      ensureNonNullable(
        resolvePathFromRoot({ path: join(ObsidianPluginRepoPaths.Src, ObsidianPluginRepoPaths.MainTs) }),
        'Could not determine the entry point for the plugin'
      )
    ],
    external: [
      'obsidian',
      'electron',
      '@codemirror/autocomplete',
      '@codemirror/collab',
      '@codemirror/commands',
      '@codemirror/language',
      '@codemirror/lint',
      '@codemirror/search',
      '@codemirror/state',
      '@codemirror/view',
      '@lezer/common',
      '@lezer/highlight',
      '@lezer/lr',
      'esbuild',
      'eslint',
      ...builtinModules
    ],
    format: 'cjs',
    keepNames: true,
    logLevel: 'info',
    minify: isProductionBuild,
    outfile: distPath,
    platform: 'node',
    plugins: [
      customEsbuildOptionsPlugin(params.customizeEsbuildOptions?.bind(params)),
      svelteWrapperPlugin(isProductionBuild),
      sassPlugin({
        sourceMap: !isProductionBuild
      }),
      renameCssPlugin(distFolder),
      preprocessPlugin(),
      fixEsmPlugin(),
      fixSourceMapsPlugin({ distPaths: [distPath, cssPath], isProductionBuild, pluginName }),
      ...params.customEsbuildPlugins ?? [],
      copyToObsidianPluginsFolderPlugin({ distFolder, isProductionBuild, obsidianConfigFolder, pluginName })
    ],
    sourcemap: isProductionBuild ? false : 'inline',
    target: 'ES2022',
    treeShaking: true
  };

  const buildContext = await context(buildOptions);
  const result = await invokeEsbuild(buildContext, isProductionBuild);
  if (!isProductionBuild) {
    watchNodeModulesAndRestart(params, buildContext);
  }
  return result;
}

/**
 * Builds the Obsidian plugin in development mode using esbuild with watch.
 *
 * In addition to esbuild's own source-graph watch, the development build also watches the plugin's
 * `node_modules` folder and restarts the whole build (including the type-check) when it changes, so a
 * dependency reinstall or rebuild is picked up.
 *
 * @param options - Optional build parameters (mode is set to Development automatically).
 * @returns A {@link Promise} that resolves to a {@link CliTaskResult} indicating the build result.
 */
// eslint-disable-next-line obsidian-dev-utils/params-options-name-match -- Intentionally shares BuildOptions with build().
export async function dev(options?: BuildOptions): Promise<CliTaskResult> {
  return await buildObsidianPlugin({ ...options, mode: BuildMode.Development });
}

/**
 * Invokes the build process with the provided build context.
 *
 * @param buildContext - The build context generated by esbuild.
 * @param isProductionBuild - A boolean indicating whether the build is a production build.
 * @returns A {@link Promise} that resolves to a {@link CliTaskResult} indicating the success or failure of the build.
 */
export async function invokeEsbuild(buildContext: BuildContext, isProductionBuild: boolean): Promise<CliTaskResult> {
  if (isProductionBuild) {
    const result = await buildContext.rebuild();
    const isSuccess = result.errors.length === 0 && result.warnings.length === 0;
    return CliTaskResult.Success(isSuccess);
  }
  await buildContext.watch();
  return CliTaskResult.DoNotExit();
}

/**
 * Watches the plugin's `node_modules` folder and restarts the development build when it changes.
 *
 * The esbuild watcher only tracks files in its build graph and only ever re-bundles — it never
 * re-runs the `build:compile` type-check, and it ignores `node_modules` changes outside the graph
 * (a reinstall, or a dependency file not currently imported). On any (debounced) change anywhere in
 * the `node_modules` tree, the current build context is disposed and the whole development build is
 * restarted, re-running the full pipeline.
 *
 * @param params - The parameters the build was started with, used to restart it.
 * @param buildContext - The esbuild context to dispose before restarting.
 */
function watchNodeModulesAndRestart(params: BuildObsidianPluginParams, buildContext: BuildContext): void {
  const nodeModulesPath = resolvePathFromRoot({ path: ObsidianPluginRepoPaths.NodeModules });
  if (!nodeModulesPath || !existsSync(nodeModulesPath)) {
    return;
  }

  let restartTimeout: ReturnType<typeof setTimeout> | undefined;
  const watcher = watch(nodeModulesPath, { recursive: true }, () => {
    if (restartTimeout) {
      // eslint-disable-next-line obsidianmd/prefer-window-timers -- Node build-tool context; `window` is not available.
      clearTimeout(restartTimeout);
    }
    // eslint-disable-next-line obsidianmd/prefer-window-timers -- Node build-tool context; `window` is not available.
    restartTimeout = setTimeout(() => {
      invokeAsyncSafely(restart);
    }, NODE_MODULES_RESTART_DEBOUNCE_IN_MILLISECONDS);
  });

  async function restart(): Promise<void> {
    console.warn('Detected changes in node_modules. Restarting the build...');
    watcher.close();
    await buildContext.dispose();
    await buildObsidianPlugin(params);
  }
}

/* v8 ignore stop */
