name: Bug report
description: Report a bug and help improve the utils
title: "[BUG] Short description of the bug"
labels: bug
assignees: mnaoumov
body:
  - type: markdown
    attributes:
      value: |
        ## Bug report

        > [!WARNING]
        >
        > A video is required for bug reproduction. Incomplete, vague, or poorly described bug reports will be closed.
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the bug. Include any relevant details.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Provide a step-by-step description.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Notice that '...'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behavior
      description: What actually happened? Include error messages if available.
    validations:
      required: true
  - type: input
    attributes:
      label: Utils version
      description: ⚠️ Must be the latest version. If not, explain why above.
      placeholder: 1.0.0
    validations:
      required: true
  - type: input
    attributes:
      label: Obsidian version
      description: ⚠️ Must be the latest version. If not, explain why above.
      placeholder: 1.3.2
    validations:
      required: true
  - type: input
    attributes:
      label: Operating system
      placeholder: Windows 10
    validations:
      required: true
  - type: textarea
    attributes:
      label: Attachments
      description: Attach a video.
      placeholder: Drag and drop files here.
  - type: dropdown
    attributes:
      label: Video
      options:
        - "Not attached. ⚠️ The bug report will be closed if the maintainer is unable to reproduce it without the attachment."
        - "Attached"
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Confirmations
      description: Ensure the following conditions are met
      options:
        - label: I have checked the utils's GitHub repository and haven't found any similar bugs
          required: true
