import {
  beforeEach,
  describe,
  expect,
  it,
  vi
} from 'vitest';

import { generate } from '../../src/script-utils/code-generator.ts';

const { mockWriteFile } = vi.hoisted(() => ({
  mockWriteFile: vi.fn()
}));

vi.mock('../../src/script-utils/node-modules.ts', async (importOriginal) => {
  const mod = await importOriginal<typeof import('../../src/script-utils/node-modules.ts')>();
  return {
    ...mod,
    writeFile: mockWriteFile
  };
});

describe('generate', () => {
  beforeEach(() => {
    mockWriteFile.mockReset();
    mockWriteFile.mockResolvedValue(undefined);
  });

  it('should prepend the generated file header', async () => {
    await generate('/output.js', ['const x = 1;', '']);
    expect(mockWriteFile).toHaveBeenCalledWith(
      '/output.js',
      expect.stringContaining('/* THIS IS A GENERATED/BUNDLED FILE BY BUILD SCRIPT */'),
      'utf-8'
    );
  });

  it('should add trailing newline if last line is non-empty', async () => {
    await generate('/output.js', ['const x = 1;']);
    const written = mockWriteFile.mock.calls[0]?.[1] as string;
    expect(written).toBe('/* THIS IS A GENERATED/BUNDLED FILE BY BUILD SCRIPT */\n\nconst x = 1;\n');
  });

  it('should not add extra trailing newline if already empty', async () => {
    await generate('/output.js', ['const x = 1;', '']);
    const written = mockWriteFile.mock.calls[0]?.[1] as string;
    expect(written).toBe('/* THIS IS A GENERATED/BUNDLED FILE BY BUILD SCRIPT */\n\nconst x = 1;\n');
  });

  it('should handle empty lines array', async () => {
    await generate('/output.js', []);
    const written = mockWriteFile.mock.calls[0]?.[1] as string;
    expect(written).toBe('/* THIS IS A GENERATED/BUNDLED FILE BY BUILD SCRIPT */\n');
  });

  it('should join multiple lines with newlines', async () => {
    await generate('/output.js', ['line1', 'line2', 'line3']);
    const written = mockWriteFile.mock.calls[0]?.[1] as string;
    expect(written).toContain('line1\nline2\nline3');
  });
});
