import {
  writeFile
} from "node:fs/promises";
import {
  basename,
  extname,
  join
} from "../src/Path.ts";
import { readdirPosix } from "../src/Fs.ts";
import { makeValidVariableName } from "../src/String.ts";
import { wrapCliTask } from "../src/bin/cli.ts";

await wrapCliTask(async () => {
  await generateIndex("src");
});

async function generateIndex(dir: string): Promise<void> {
  const dirents = await readdirPosix(dir, { withFileTypes: true });
  const lines: string[] = ["/* THIS IS A GENERATED/BUNDLED FILE BY BUILD SCRIPT */", ""];
  for (const dirent of dirents) {
    if (dirent.name === "index.ts" || dirent.name === "@types" || dirent.name.endsWith(".d.ts")) {
      continue;
    }
    let sourceFile: string;
    let name: string;
    if (dirent.isDirectory()) {
      await generateIndex(`${dir}/${dirent.name}`);
      sourceFile = `./${dirent.name}/index.ts`;
      name = dirent.name;
    } else {
      const extension = extname(dirent.name);
      name = basename(dirent.name, extension);
      sourceFile = `./${dirent.name}`;
    }

    lines.push(`export * as ${makeValidVariableName(name)} from "${sourceFile}";`);
  }

  if (lines.at(-1)) {
    lines.push("");
  }

  await writeFile(join(dir, "index.ts"), lines.join("\n"), "utf-8");
}
