import esbuild, { type BuildOptions } from "esbuild";
import {
  readFile,
  writeFile
} from "node:fs/promises";
import process from "node:process";
import { readNpmPackage } from "../src/Npm.ts";

const npmPackage = await readNpmPackage();

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const buildOptions: BuildOptions = {
  banner: {
    js: banner
  },
  bundle: false,
  entryPoints: ["src/**/*.ts"],
  format: "cjs",
  logLevel: "info",
  outdir: "dist/lib",
  platform: "node",
  sourcemap: "inline",
  target: "ESNext",
  treeShaking: true,
  write: false,

  plugins: [
    {
      name: "preprocess",
      setup(build): void {
        build.onLoad({ filter: /\.(js|ts|cjs|mjs|cts|mts)$/ }, async (args) => {
          let contents = await readFile(args.path, "utf8");

          if (contents.includes("import.meta.url")) {
            contents = "const import_meta_url = require(\"node:url\").pathToFileURL(__filename);\n"
              + contents.replaceAll("import.meta.url", "import_meta_url");
          }

          contents = contents.replaceAll("${NODE_PACKAGE_VERSION}", npmPackage.version);

          return {
            contents,
            loader: "ts"
          };
        });
      },
    },
    {
      name: "rename-extension",
      setup(build): void {
        build.onEnd(async (result) => {
          for (const file of result.outputFiles ?? []) {
            if (!file.path.endsWith(".js") || file.path.endsWith(".d.js")) {
              continue;
            }
            const newPath = file.path.replace(/\.js$/, ".cjs");
            const newText = file.text.replaceAll(/require\("([^"]+)\.ts"\)/g, "require(\"$1.cjs\")");
            await writeFile(newPath, newText);
          }
        });
      }
    }
  ]
};

const context = await esbuild.context(buildOptions);

await context.rebuild();
process.exit(0);
