import esbuild from "esbuild";
import process from "node:process";

const banner = `#!/usr/bin/env node

/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const context = await esbuild.context({
  banner: {
    js: banner
  },
  entryPoints: ["src/bin/cli.ts"],
  bundle: true,
  format: "cjs",
  target: "ESNext",
  logLevel: "info",
  sourcemap: "inline",
  treeShaking: true,
  outfile: "dist/bin/cli.cjs"
});

await context.rebuild();
process.exit(0);
