import esbuild from "esbuild";
import { readFile } from "node:fs/promises";
import process from "node:process";

const banner = `#!/usr/bin/env node

/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const context = await esbuild.context({
  banner: {
    js: banner
  },
  bundle: true,
  entryPoints: ["src/bin/cli.ts"],
  external: ["esbuild"],
  format: "cjs",
  logLevel: "info",
  outfile: "dist/bin/cli.cjs",
  platform: "node",
  sourcemap: "inline",
  target: "ESNext",
  treeShaking: true,

  plugins: [
    {
      name: "preprocess",
      setup(build): void {
        build.onLoad({ filter: /\.(js|ts|cjs|mjs|cts|mts)$/ }, async (args) => {
          let contents = await readFile(args.path, "utf8");
          contents = contents.replace(/import\.meta\.url/g, "__filename");

          return {
            contents,
            loader: "ts"
          };
        });
      },
    }
  ]
});

await context.rebuild();
process.exit(0);
