import { writeFile } from "node:fs/promises";

export async function generate(path: string, lines: string[]): Promise<void> {
  if (lines.at(-1)) {
    lines.push("");
  }
  lines.unshift("/* THIS IS A GENERATED/BUNDLED FILE BY BUILD SCRIPT */", "");
  await writeFile(path, lines.join("\n"), "utf-8");
}
